### ISSUE TITLE
repo error when initializing the client

### ISSUE THREAD

**Issue by mtzfactory** [gumstix/yocto-manifest#65]
Hi,

I'm not able to initialize the repo client, I get the following error but as you can see at the log's end, I already have configured user.mail and user.name...

What I'm missing?

```
ulocal@mlocal:~/dev/gumstix/yocto$ repo init -u git://github.com/gumstix/yocto-manifest.git
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
Get git://github.com/gumstix/yocto-manifest.git
remote: Counting objects: 379, done.
remote: Total 379 (delta 0), reused 0 (delta 0), pack-reused 379
Receiving objects: 100% (379/379), 61.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (114/114), done.
From git://github.com/gumstix/yocto-manifest
 * [new branch]      dev        -> origin/dev
 * [new branch]      master     -> origin/master
 * [new tag]         daisy      -> daisy
 * [new tag]         danny      -> danny
 * [new tag]         dizzy      -> dizzy
 * [new tag]         dizzy-1.7.2 -> dizzy-1.7.2
 * [new tag]         dora       -> dora
 * [new tag]         dylan      -> dylan
 * [new tag]         fido       -> fido

Traceback (most recent call last):
  File "/home/ulocal/dev/gumstix/yocto/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/home/ulocal/dev/gumstix/yocto/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/home/ulocal/dev/gumstix/yocto/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/ulocal/dev/gumstix/yocto/.repo/repo/subcmds/init.py", line 395, in Execute
    self._ConfigureUser()
  File "/home/ulocal/dev/gumstix/yocto/.repo/repo/subcmds/init.py", line 289, in _ConfigureUser
    name  = self._Prompt('Your Name', mp.UserName)
  File "/home/ulocal/dev/gumstix/yocto/.repo/repo/project.py", line 703, in UserName
    self._LoadUserIdentity()
  File "/home/ulocal/dev/gumstix/yocto/.repo/repo/project.py", line 716, in _LoadUserIdentity
    u = self.bare_git.var('GIT_COMMITTER_IDENT')
  File "/home/ulocal/dev/gumstix/yocto/.repo/repo/project.py", line 2644, in runner
    p.stderr))
error.GitError: manifests var: 
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'ulocal@mlocal.(none)')
ulocal@mlocal:~/dev/gumstix/yocto$ git config --list
user.mail=x.y.z@gmail.com
user.name=xyz
```

**Comment by ashcharles** [comment]
I haven't seen this error before but I noticed a potential typo that might cause a problem?
user.email vs user.mail?

**Comment by arunbharadwaj** [comment]
I noticed a typo in your repo init commandline: You seem to be missing a
dot in "yocto-manifest.git"
